vaccel-virtio: Add CI checks and integrate release orchestration
Add CI PR checks, improve build workflow and integrate vAccel automatic
release orchestration.

CI:
- Remove PR `lockdown` workflow
- Add dependabot config for GitHub Actions dependency updates
- Split build logic into `build-docker-image` reusable workflow
- Add PR build and linter checks
- Integrate vAccel automatic release orchestration
- General code style cleanup

Build:
- Add `.clang-format` and format docker scripts
- Improve `Dockerfile`:
  - Use venv for Python dependencies
  - Use prebuilt vAccel artifacts instead of building from source
  - Add `BUILD_TYPE` arg to configure vAccel and QEMU build types
  - Skip QEMU virtqueue patch application since size limitations have
    been removed with recently introduced request splitting

Signed-off-by: Kostis Papazafeiropoulos <papazof@gmail.com>

diff --git a/subprojects/vaccel-virtio/docker/qemu-ifup b/subprojects/vaccel-virtio/docker/qemu-ifup
--- a/subprojects/vaccel-virtio/docker/qemu-ifup
+++ b/subprojects/vaccel-virtio/docker/qemu-ifup
@@ -8,14 +8,14 @@ PATH=$PATH:/sbin:/usr/sbin
 ip=$(which ip)
 
 if [ -n "$ip" ]; then
-   ip link set "$1" up
+	ip link set "$1" up
 else
-   brctl=$(which brctl)
-   if [ ! "$ip" -o ! "$brctl" ]; then
-     echo "W: $0: not doing any bridge processing: neither ip nor brctl utility not found" >&2
-     exit 0
-   fi
-   ifconfig "$1" 0.0.0.0 up
+	brctl=$(which brctl)
+	if [ ! "$ip" ] || [ ! "$brctl" ]; then
+		echo "W: $0: not doing any bridge processing: neither ip nor brctl utility not found" >&2
+		exit 0
+	fi
+	ifconfig "$1" 0.0.0.0 up
 fi
 
 switch=virbr0
@@ -25,14 +25,14 @@ switch=virbr0
 # interface is actually a bridge.
 # It is possible to have several default routes too
 for br in $switch; do
-    if [ -d /sys/class/net/$br/bridge/. ]; then
-        if [ -n "$ip" ]; then
-          ip link set "$1" master "$br"
-        else
-          brctl addif $br "$1"
-        fi
-        exit	# exit with status of the previous command
-    fi
+	if [ -d "/sys/class/net/$br/bridge/." ]; then
+		if [ -n "$ip" ]; then
+			ip link set "$1" master "$br"
+		else
+			brctl addif "$br" "$1"
+		fi
+		exit # exit with status of the previous command
+	fi
 done
 
 echo "W: $0: no bridge for guest interface found" >&2
